import { Activity } from "./types";

/**
 * ACTIVITY DATABASE
 *
 * This file contains all activities that the quiz can recommend.
 * Currently populated with sample data — replace with real scraped data
 * from your Outscraper CSV.
 *
 * TO UPDATE: Edit this file directly, or use the admin panel at /admin/activities
 *
 * LISTING TIERS:
 * - "spotlight" ($199/mo) — appears in quiz with +15 bonus, max 3 per category
 * - "premium" ($99/mo) — appears in quiz with +8 bonus
 * - "enhanced" ($49/mo) — appears in quiz with +3 bonus
 * - "free" ($0) — does NOT appear in quiz results, directory only
 */

const DIRECTORY_BASE = process.env.NEXT_PUBLIC_DIRECTORY_URL || "https://forsythkidsguide.com";

export const activities: Activity[] = [
  {
    id: "1",
    name: "Cumming Dance Academy",
    category: "Dance & Ballet",
    description: "Premier dance studio offering ballet, jazz, tap, and contemporary for ages 3 through teen. Competition teams and recreational classes available with experienced instructors who nurture both technique and confidence.",
    ageRanges: ["3-5", "6-8", "9-12", "13+"],
    personalityMatch: ["creative", "social", "everything"],
    interestMatch: ["individual", "creative-expression"],
    scheduleOptions: ["weekday-afternoon", "weekday-evening", "weekends"],
    priceRange: "100-200",
    location: "south",
    listingTier: "spotlight",
    website: "https://cummingdanceacademy.com",
    phone: "(770) 555-0101",
    address: "410 Peachtree Pkwy, Cumming GA 30041",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/cumming-dance-academy/`,
    rating: 4.9,
    reviewCount: 127,
    badges: ["Featured Partner", "Staff Pick"],
  },
  {
    id: "2",
    name: "Mathnasium of Cumming",
    category: "Tutoring & Academic",
    description: "Customized math learning for K-12 students. The Mathnasium Method builds deep understanding and confidence through personalized learning plans tailored to each student's needs and goals.",
    ageRanges: ["6-8", "9-12", "13+"],
    personalityMatch: ["academic", "everything"],
    interestMatch: ["academic-enrichment", "individual"],
    scheduleOptions: ["weekday-afternoon", "weekday-evening"],
    priceRange: "200-plus",
    location: "cumming",
    listingTier: "premium",
    website: "https://mathnasium.com/cumming",
    phone: "(770) 555-0102",
    address: "1855 Market Place Blvd, Cumming GA 30041",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/mathnasium-cumming/`,
    rating: 4.8,
    reviewCount: 89,
    badges: ["Featured Partner"],
  },
  {
    id: "3",
    name: "American Martial Arts Academy",
    category: "Martial Arts",
    description: "Building character through martial arts since 2005. Programs include Taekwondo, Brazilian Jiu-Jitsu, and self-defense for all ages starting at 4. Focus on discipline, respect, and confidence.",
    ageRanges: ["3-5", "6-8", "9-12", "13+"],
    personalityMatch: ["athletic", "social", "everything"],
    interestMatch: ["individual", "team-sports"],
    scheduleOptions: ["weekday-afternoon", "weekday-evening", "weekends"],
    priceRange: "100-200",
    location: "south",
    listingTier: "spotlight",
    website: "https://americanmartialarts.com",
    phone: "(770) 555-0103",
    address: "5765 Bethelview Rd, Cumming GA 30040",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/american-martial-arts/`,
    rating: 4.9,
    reviewCount: 203,
    badges: ["Featured Partner", "Staff Pick"],
  },
  {
    id: "4",
    name: "Forsyth County Aquatic Center",
    category: "Swim Lessons",
    description: "Year-round swim lessons for babies through adults at the county's premier aquatic facility. Red Cross certified instructors with small class sizes and multiple skill levels available.",
    ageRanges: ["under-3", "3-5", "6-8", "9-12"],
    personalityMatch: ["athletic", "social", "everything"],
    interestMatch: ["individual", "team-sports"],
    scheduleOptions: ["weekday-afternoon", "weekday-evening", "weekends", "flexible"],
    priceRange: "50-100",
    location: "anywhere",
    listingTier: "enhanced",
    website: "https://forsythco.com/aquatics",
    phone: "(770) 555-0104",
    address: "2500 Castleberry Rd, Cumming GA 30040",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/forsyth-aquatic-center/`,
    rating: 4.6,
    reviewCount: 312,
    badges: [],
  },
  {
    id: "5",
    name: "Code Ninjas Cumming",
    category: "STEM & Coding",
    description: "Kids learn to code by building video games in a fun, safe environment. Our proven curriculum takes kids from white belt to black belt in coding, building real programming skills they'll use forever.",
    ageRanges: ["6-8", "9-12", "13+"],
    personalityMatch: ["academic", "creative", "everything"],
    interestMatch: ["academic-enrichment", "individual"],
    scheduleOptions: ["weekday-afternoon", "weekends"],
    priceRange: "200-plus",
    location: "south",
    listingTier: "premium",
    website: "https://codeninjas.com/cumming",
    phone: "(770) 555-0105",
    address: "5935 Cumming Hwy, Sugar Hill GA 30518",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/code-ninjas-cumming/`,
    rating: 4.7,
    reviewCount: 56,
    badges: ["Featured Partner"],
  },
  {
    id: "6",
    name: "Gymfinity Gymnastics",
    category: "Gymnastics & Cheer",
    description: "Recreational and competitive gymnastics for ages 18 months and up. Certified coaches in a state-of-the-art facility with spring floors, vault runway, and Olympic-grade equipment.",
    ageRanges: ["under-3", "3-5", "6-8", "9-12"],
    personalityMatch: ["athletic", "social", "everything"],
    interestMatch: ["individual", "team-sports"],
    scheduleOptions: ["weekday-afternoon", "weekday-evening", "weekends"],
    priceRange: "100-200",
    location: "cumming",
    listingTier: "spotlight",
    website: "https://gymfinitygymnastics.com",
    phone: "(770) 555-0106",
    address: "1210 Buford Hwy, Cumming GA 30041",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/gymfinity/`,
    rating: 4.8,
    reviewCount: 178,
    badges: ["Featured Partner", "Staff Pick"],
  },
  {
    id: "7",
    name: "Bach to Rock Cumming",
    category: "Music Lessons",
    description: "Music lessons for all ages and skill levels in guitar, piano, drums, voice, and band programs. Students perform in real venues and record in a professional studio environment.",
    ageRanges: ["6-8", "9-12", "13+"],
    personalityMatch: ["creative", "social", "everything"],
    interestMatch: ["creative-expression", "individual"],
    scheduleOptions: ["weekday-afternoon", "weekday-evening", "weekends"],
    priceRange: "100-200",
    location: "south",
    listingTier: "premium",
    website: "https://bachtorock.com/cumming",
    phone: "(770) 555-0107",
    address: "4488 Bethelview Rd, Cumming GA 30040",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/bach-to-rock/`,
    rating: 4.7,
    reviewCount: 92,
    badges: ["Featured Partner"],
  },
  {
    id: "8",
    name: "Kidz Art Forsyth",
    category: "Art & Creative",
    description: "Inspiring creativity through painting, pottery, mixed media, and digital art. Small class sizes ensure personalized attention for every young artist. Birthday parties and holiday camps available.",
    ageRanges: ["3-5", "6-8", "9-12"],
    personalityMatch: ["creative", "academic", "everything"],
    interestMatch: ["creative-expression", "individual"],
    scheduleOptions: ["weekday-afternoon", "weekends"],
    priceRange: "50-100",
    location: "cumming",
    listingTier: "enhanced",
    website: "https://kidzart.com",
    phone: "(770) 555-0108",
    address: "302 Canton Hwy, Cumming GA 30040",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/kidz-art-forsyth/`,
    rating: 4.5,
    reviewCount: 34,
    badges: [],
  },
  {
    id: "9",
    name: "i9 Sports Forsyth County",
    category: "Sports Training & Leagues",
    description: "Age-appropriate sports leagues including flag football, soccer, basketball, and baseball. Focus on fun, sportsmanship, and development with trained, background-checked coaches.",
    ageRanges: ["3-5", "6-8", "9-12"],
    personalityMatch: ["athletic", "social", "everything"],
    interestMatch: ["team-sports", "outdoor"],
    scheduleOptions: ["weekends", "weekday-evening"],
    priceRange: "100-200",
    location: "anywhere",
    listingTier: "spotlight",
    website: "https://i9sports.com/forsyth",
    phone: "(770) 555-0109",
    address: "Various Forsyth County locations",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/i9-sports/`,
    rating: 4.6,
    reviewCount: 145,
    badges: ["Featured Partner", "Staff Pick"],
  },
  {
    id: "10",
    name: "Camp Horizon Forsyth",
    category: "Summer Camps",
    description: "The ultimate summer experience with outdoor adventures, STEM projects, arts, sports, and swimming. Full-day and half-day options for ages 5-14 with experienced camp counselors.",
    ageRanges: ["3-5", "6-8", "9-12"],
    personalityMatch: ["athletic", "creative", "social", "everything"],
    interestMatch: ["outdoor", "team-sports", "creative-expression"],
    scheduleOptions: ["flexible"],
    priceRange: "200-plus",
    location: "north",
    listingTier: "spotlight",
    website: "https://camphorizon.com",
    phone: "(770) 555-0110",
    address: "6800 Shiloh Rd, Cumming GA 30028",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/camp-horizon/`,
    rating: 4.8,
    reviewCount: 67,
    badges: ["Featured Partner", "Staff Pick"],
  },
  {
    id: "11",
    name: "The Little Gym of Cumming",
    category: "Gymnastics & Cheer",
    description: "Serious fun with a purpose for ages 4 months to 12 years. Gymnastics, dance, sports skills, and enrichment classes in a nurturing, non-competitive environment.",
    ageRanges: ["under-3", "3-5", "6-8", "9-12"],
    personalityMatch: ["athletic", "social", "everything"],
    interestMatch: ["individual", "team-sports"],
    scheduleOptions: ["weekday-afternoon", "weekends"],
    priceRange: "100-200",
    location: "south",
    listingTier: "enhanced",
    website: "https://thelittlegym.com/cumming",
    phone: "(770) 555-0111",
    address: "5285 Bethelview Rd, Cumming GA 30040",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/little-gym-cumming/`,
    rating: 4.7,
    reviewCount: 88,
    badges: [],
  },
  {
    id: "12",
    name: "Kumon of Cumming",
    category: "Tutoring & Academic",
    description: "Self-paced math and reading programs for preschool through high school. Daily practice worksheets build strong academic foundations and independent study habits.",
    ageRanges: ["3-5", "6-8", "9-12", "13+"],
    personalityMatch: ["academic", "everything"],
    interestMatch: ["academic-enrichment", "individual"],
    scheduleOptions: ["weekday-afternoon", "weekday-evening"],
    priceRange: "100-200",
    location: "cumming",
    listingTier: "enhanced",
    website: "https://kumon.com/cumming",
    phone: "(770) 555-0112",
    address: "410 Peachtree Pkwy #208, Cumming GA 30041",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/kumon-cumming/`,
    rating: 4.3,
    reviewCount: 42,
    badges: [],
  },
  {
    id: "13",
    name: "Lanier Stars Soccer Club",
    category: "Sports Training & Leagues",
    description: "Competitive and recreational youth soccer serving North Georgia. Professional coaching staff with development-focused programs from U4 through U19 age groups.",
    ageRanges: ["3-5", "6-8", "9-12", "13+"],
    personalityMatch: ["athletic", "social", "everything"],
    interestMatch: ["team-sports", "outdoor"],
    scheduleOptions: ["weekday-evening", "weekends"],
    priceRange: "100-200",
    location: "anywhere",
    listingTier: "premium",
    website: "https://lanierstarssoccer.com",
    phone: "(770) 555-0113",
    address: "Central Park, Cumming GA 30040",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/lanier-stars/`,
    rating: 4.5,
    reviewCount: 98,
    badges: ["Featured Partner"],
  },
  {
    id: "14",
    name: "Primrose School of Cumming",
    category: "Preschool Enrichment",
    description: "Balanced Learning approach for infants through pre-K and after-school. Character development, STEM exploration, early literacy, and physical activity in a warm, nurturing setting.",
    ageRanges: ["under-3", "3-5"],
    personalityMatch: ["social", "creative", "academic", "everything"],
    interestMatch: ["academic-enrichment", "creative-expression", "team-sports"],
    scheduleOptions: ["weekday-afternoon", "flexible"],
    priceRange: "200-plus",
    location: "cumming",
    listingTier: "enhanced",
    website: "https://primroseschools.com/cumming",
    phone: "(770) 555-0114",
    address: "1215 Market Place Blvd, Cumming GA 30041",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/primrose-cumming/`,
    rating: 4.6,
    reviewCount: 73,
    badges: [],
  },
  {
    id: "15",
    name: "Forsyth County Parks & Rec",
    category: "Outdoor & Adventure",
    description: "Affordable outdoor programs including hiking clubs, nature camps, fishing clinics, and adventure sports across Forsyth County's beautiful parks and trail system.",
    ageRanges: ["6-8", "9-12", "13+"],
    personalityMatch: ["athletic", "academic", "everything"],
    interestMatch: ["outdoor", "team-sports"],
    scheduleOptions: ["weekends", "flexible"],
    priceRange: "under-50",
    location: "anywhere",
    listingTier: "enhanced",
    website: "https://forsythco.com/parks",
    phone: "(770) 555-0115",
    address: "Multiple Forsyth County locations",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/forsyth-parks/`,
    rating: 4.4,
    reviewCount: 156,
    badges: [],
  },
  {
    id: "16",
    name: "Cumming Playhouse",
    category: "Theater & Drama",
    description: "Youth theater productions, acting camps, and improv classes. Kids build confidence, public speaking skills, and lasting friendships while having a blast on stage.",
    ageRanges: ["6-8", "9-12", "13+"],
    personalityMatch: ["creative", "social", "everything"],
    interestMatch: ["creative-expression"],
    scheduleOptions: ["weekday-evening", "weekends"],
    priceRange: "50-100",
    location: "cumming",
    listingTier: "premium",
    website: "https://cummingplayhouse.com",
    phone: "(770) 555-0116",
    address: "221 School St, Cumming GA 30040",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/cumming-playhouse/`,
    rating: 4.9,
    reviewCount: 41,
    badges: ["Featured Partner"],
  },
  {
    id: "17",
    name: "TopFlight Cheer Academy",
    category: "Gymnastics & Cheer",
    description: "All-star competitive cheerleading and tumbling for ages 3 and up. Building athletes, confidence, and lifelong friendships through team excellence and dedicated coaching.",
    ageRanges: ["3-5", "6-8", "9-12", "13+"],
    personalityMatch: ["athletic", "social", "everything"],
    interestMatch: ["team-sports", "individual"],
    scheduleOptions: ["weekday-evening", "weekends"],
    priceRange: "200-plus",
    location: "south",
    listingTier: "premium",
    website: "https://topflightcheer.com",
    phone: "(770) 555-0117",
    address: "5915 Bethelview Rd, Cumming GA 30040",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/topflight-cheer/`,
    rating: 4.8,
    reviewCount: 63,
    badges: ["Featured Partner"],
  },
  {
    id: "18",
    name: "Kindermusik with Miss Sarah",
    category: "Music Lessons",
    description: "Award-winning early childhood music and movement classes for newborns through age 7. Research-based curriculum fostering cognitive development, creativity, and social skills.",
    ageRanges: ["under-3", "3-5", "6-8"],
    personalityMatch: ["creative", "social", "everything"],
    interestMatch: ["creative-expression", "individual"],
    scheduleOptions: ["weekday-afternoon", "weekends"],
    priceRange: "50-100",
    location: "cumming",
    listingTier: "enhanced",
    website: "https://kindermusik.com",
    phone: "(770) 555-0118",
    address: "Studio location, Cumming GA 30040",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/kindermusik/`,
    rating: 5.0,
    reviewCount: 29,
    badges: [],
  },
  {
    id: "19",
    name: "Launch Trampoline Park",
    category: "Birthday Parties & Events",
    description: "Indoor trampoline park with open jump, dodgeball, foam pits, and ninja warrior courses. Birthday party packages and group events available daily for all ages.",
    ageRanges: ["3-5", "6-8", "9-12", "13+"],
    personalityMatch: ["athletic", "social", "everything"],
    interestMatch: ["team-sports", "outdoor", "individual"],
    scheduleOptions: ["weekday-afternoon", "weekday-evening", "weekends", "flexible"],
    priceRange: "under-50",
    location: "south",
    listingTier: "enhanced",
    website: "https://launchtrampolinepark.com",
    phone: "(770) 555-0119",
    address: "5500 Cumming Hwy, Sugar Hill GA 30518",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/launch-trampoline/`,
    rating: 4.3,
    reviewCount: 267,
    badges: [],
  },
  {
    id: "20",
    name: "Sylvan Learning of Cumming",
    category: "Tutoring & Academic",
    description: "Personalized tutoring in reading, math, writing, and test prep with proven methods and measurable results. Serving students from kindergarten through 12th grade.",
    ageRanges: ["6-8", "9-12", "13+"],
    personalityMatch: ["academic", "everything"],
    interestMatch: ["academic-enrichment", "individual"],
    scheduleOptions: ["weekday-afternoon", "weekday-evening"],
    priceRange: "200-plus",
    location: "cumming",
    listingTier: "premium",
    website: "https://sylvanlearning.com/cumming",
    phone: "(770) 555-0120",
    address: "1695 Market Pl Blvd, Cumming GA 30041",
    imageUrl: "/images/placeholder.jpg",
    directoryUrl: `${DIRECTORY_BASE}/listing/sylvan-cumming/`,
    rating: 4.6,
    reviewCount: 51,
    badges: ["Featured Partner"],
  },
];
